### PR TITLE
Update for laravel 4.2.x

### PR DESCRIPTION
**Pull request by florentsorel**

### CODE REVIEW

**Comment by fojuth** [comment]
Thanks for the pull request. Have you tested it? Does it work properly on Laravel 4.2? I didn't have the time to check this.

**Comment by jgoyvaerts** [comment]
Shouldn't the php version be updated too?
From http://laravel.com/docs/upgrade#upgrade-4.2 :
Laravel 4.2 requires PHP 5.4.0 or greater.

**Comment by fojuth** [comment]
@jgoyvaerts Sure, your right. I still don't have time to sit down to this and test everything. If I'll be able to, I'll make some branches / tags for Laravel 4.2 support.

**Comment by svpernova09** [comment]
This won't work with rcrowe/TwigBridge 0.6 without changes. See #8 

Not certain if Laravel 4.2 & TwigBridge 0.5 works, I ran into issues with other dependencies and was forced to go to TwigBridge 0.6

**Comment by fojuth** [comment]
Closing this PR as another one was merged, providing support for Laravel 4.2.*

**Pull request closed without merging**
